# Generated by Django 3.2.13 on 2022-05-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_emailsubscriber_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='postContent/')),
                ('imageAltText', models.CharField(blank=True, default='image', max_length=200, null=True)),
            ],
        ),
    ]
