# Generated by Django 3.2.13 on 2022-04-22 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Handles',
            new_name='Handle',
        ),
    ]
