# Generated by Django 3.2.13 on 2022-04-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0002_rename_handles_handle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
