# Generated by Django 3.2.13 on 2022-04-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0004_alter_contest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='isParsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='isSend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='tryCount',
            field=models.IntegerField(default=0),
        ),
    ]
